<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="1" total="3" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<a href= '/Users/VibhorAgarwal/TGAF_Mobile/screenshots/loginTest2019-07-15-03-15-27.png'target='_blank' ><img src='/Users/VibhorAgarwal/TGAF_Mobile/screenshots/loginTest2019-07-15-03-15-27.png'>loginTest2019-07-15-03-15-27</a>]]>
    </line>
  </reporter-output>
  <suite name="Demo Test Suite" duration-ms="139564" started-at="2019-07-15T09:43:12Z" finished-at="2019-07-15T09:45:32Z">
    <groups>
    </groups>
    <test name="DemoTestHdfc" duration-ms="139564" started-at="2019-07-15T09:43:12Z" finished-at="2019-07-15T09:45:32Z">
      <class name="DemoTest">
        <test-method status="PASS" signature="before()[pri:0, instance:DemoTest@bcec361]" name="before" is-config="true" duration-ms="40792" started-at="2019-07-15T09:42:31Z" finished-at="2019-07-15T09:43:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="PASS" signature="classDataInitializer()[pri:0, instance:DemoTest@bcec361]" name="classDataInitializer" is-config="true" duration-ms="22" started-at="2019-07-15T09:43:12Z" finished-at="2019-07-15T09:43:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classDataInitializer -->
        <test-method status="PASS" signature="initializeExtentTest(java.lang.reflect.Method)[pri:0, instance:DemoTest@bcec361]" name="initializeExtentTest" is-config="true" duration-ms="10" started-at="2019-07-15T09:43:12Z" finished-at="2019-07-15T09:43:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void DemoTest.loginTest(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeExtentTest -->
        <test-method status="SKIP" signature="loginTest(java.lang.reflect.Method)[pri:0, instance:DemoTest@bcec361]" name="loginTest" duration-ms="134889" started-at="2019-07-15T09:43:12Z" finished-at="2019-07-15T09:45:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void DemoTest.loginTest(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Step-1: User failed to login!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Step-1: User failed to login!!
at org.springframework.util.Assert.isTrue(Assert.java:118)
at DemoTest.loginTest(DemoTest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:DemoTest@bcec361]" name="afterMethod" is-config="true" duration-ms="194" started-at="2019-07-15T09:45:27Z" finished-at="2019-07-15T09:45:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=SKIP method=DemoTest.loginTest(java.lang.reflect.Method)[pri:0, instance:DemoTest@bcec361] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="initializeExtentTest(java.lang.reflect.Method)[pri:0, instance:DemoTest@bcec361]" name="initializeExtentTest" is-config="true" duration-ms="1" started-at="2019-07-15T09:45:27Z" finished-at="2019-07-15T09:45:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void DemoTest.loginTest(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeExtentTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.reflect.Method)[pri:0, instance:DemoTest@bcec361]" name="loginTest" duration-ms="1" started-at="2019-07-15T09:45:27Z" finished-at="2019-07-15T09:45:27Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:DemoTest@bcec361]" name="afterMethod" is-config="true" duration-ms="4429" started-at="2019-07-15T09:45:27Z" finished-at="2019-07-15T09:45:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=DemoTest.loginTest(java.lang.reflect.Method)[pri:0, instance:DemoTest@bcec361] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href= '/Users/VibhorAgarwal/TGAF_Mobile/screenshots/loginTest2019-07-15-03-15-27.png'target='_blank' ><img src='/Users/VibhorAgarwal/TGAF_Mobile/screenshots/loginTest2019-07-15-03-15-27.png'>loginTest2019-07-15-03-15-27</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:DemoTest@bcec361]" name="closeDriver" is-config="true" duration-ms="0" started-at="2019-07-15T09:45:32Z" finished-at="2019-07-15T09:45:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method status="PASS" signature="tearDownSuite()[pri:0, instance:DemoTest@bcec361]" name="tearDownSuite" is-config="true" duration-ms="1165" started-at="2019-07-15T09:45:32Z" finished-at="2019-07-15T09:45:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSuite -->
      </class> <!-- DemoTest -->
    </test> <!-- DemoTestHdfc -->
  </suite> <!-- Demo Test Suite -->
</testng-results>
